#!/bin/bash
cd ~/
nohup xterm -e htop > /dev/null &
nohup xterm -e watch -n 5 acpi -V > /dev/null &
nohup xterm -e alsamixer > /dev/null &
nohup xterm -e mocp > /dev/null &
nohup xterm -e /home/def/scripts/countdown.sh > /dev/null &
nohup xterm -e sudo -s > /dev/null &
