#!/bin/bash

#key-mon& # Display each keystroke on screen
#cvlc v4l2:// :v4l2-vdev=”/dev/video0”& # Display 

ffmpeg -framerate 20 -video_size 1280x720 -f x11grab -i :0.0+0,20 -f alsa -ac 2 -i pulse -vcodec libx264 -crf 0 -preset medium -acodec pcm_s16le $(date +%Y_%m_%d-%H_%M_%S)_$1.avi
#ffmpeg -i output.flv -acodec ... -vcodec ... final.flv
