#!/bin/bash

#sudo mount /dev/mmcblk0p1 /media/usb0
if [ "$#" -eq "3" ]; then
	sudo mount /dev/sdcard /media/usb0
fi

rsync --progress --remove-source-files -r /media/EOS_DIGITAL/DCIM /home/def/removable/usb/Photos/$(date +%Y%m%d_%H%M_%S)_$1

sudo umount /media/EOS_DIGITAL
